development: &mysql
  adapter:    mysql2
  encoding:   utf8
  reconnect:  false
  database:   next_development
  pool: 5
  username:   root
  password:
  socket: <%= ['/private/tmp/mysql.sock', '/var/lib/mysql/mysql.sock', '/var/run/mysqld/mysqld.sock'].detect{ |socket| File.exist?(socket) } %>

test:
  <<: *mysql
  database:   next_test
